version: 0.0
os: linux
files:
  - source: /deploy
    destination: /home/ubuntu/app/deploy
    overwrite: yes

permissions:
    - object: /home/ubuntu/app/deploy
      pattern: "**"
      owner: ubuntu
      group: ubuntu

hooks:
  AfterInstall:
    - location: ./deploy/scripts/runNewWas.sh
      timeout: 100
      runas: ubuntu
    - location: ./deploy/scripts/healthCheck.sh
      timeout: 100
      runas: root
    - location: ./deploy/scripts/switchPort.sh
      timeout: 100
      runas: root
    - location: ./deploy/scripts/stopServer.sh
      timeout: 100
      runas: root