version: 0.0
os: linux
files:
  - source: /deploy
    destination: /home/ubuntu/app/deploy
    overwrite: yes

permissions:
    - object: /home/ubuntu/app/deploy
      pattern: "**"
      owner: root
      group: root

hooks:
  AfterInstall:
    - location: ./deploy/scripts/beforeInstall.sh
      timeout: 100
      runas: root
    - location: ./deploy/scripts/beforeInstall.sh
      timeout: 100
      runas: root
#  ApplicationStop: