spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  access_key: ${JWT_ACCESS_KEY}
  refresh_key: ${JWT_REFRESH_KEY}
  access_expired_min: 525600
  refresh_expired_day: 30
  bearer_prefix: "Bearer "

oauth2:
  client:
    kakao:
      content_type: ${URL_ENCODED_CONTENT_TYPE}
      grant_type: ${GRANT_TYPE}
      client_id: ${KAKAO_CLIENT_ID}
      login_page_url: ${KAKAO_LOGIN_PAGE_URL}
    google:
      content_type: ${URL_ENCODED_CONTENT_TYPE}
      grant_type: ${GRANT_TYPE}
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
      login_page_url: ${GOOGLE_LOGIN_PAGE_URL}
