name: Integration
run-name: ${{ github.event_name }} ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches: [ main, hotfix/**, releases/**, develop, feature/** ]
  pull_request:
    branches: [ main, hotfix/**, releases/**, develop, feature/** ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'dev' }}
    steps:
      -
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash